blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='post_list'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='post_view'),
    path('create/', never_cache(PostCreateView.as_view()), name='post_create'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='post_edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomePageView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, LogListView, active_toggle, MessageListView, \
    MessageCreateView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('list/', MailingListView.as_view(), name='mailing_list'),
    path('view/<int:pk>/', MailingDetailView.as_view(), name='mailing_view'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('log_list/', LogListView.as_view(), name='log_list'),
    path('activity/<int:pk>/', active_toggle, name='activity')

]

mailing/models.py
from django.db import models
from django.db.models.functions import datetime
from config import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    """Кто получает рассылку"""
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    surname = models.CharField(max_length=50, verbose_name='Отчество', **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Почта', unique=True)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.last_name} {self.first_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('last_name', 'first_name')


class Message(models.Model):
    """Сообщение рассылки"""
    title = models.CharField(max_length=100, verbose_name='Тема письма', default='Без темы')
    text = models.TextField(verbose_name='Содержание', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('title',)


class Mailing(models.Model):
    """Настройки рассылки"""
    """Статусы рассылки"""
    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    ]
    """Периодичность рассылки"""
    PERIOD_CHOICES = [
        ('once', '1 раз'),
        ('daily', 'Ежедневно'),
        ('weekly', 'Еженедельно'),
        ('monthly', 'Ежемесячно'),
    ]

    start_point = models.DateTimeField(verbose_name='Начать рассылку', default=datetime.datetime.now)
    stop_point = models.DateTimeField(verbose_name='Завершить рассылку', default=datetime.datetime.now)
    period = models.CharField(max_length=20, verbose_name='Периодичность', choices=PERIOD_CHOICES, default='once')
    status = models.CharField(max_length=20, verbose_name='Статус выполнения', choices=STATUS_CHOICES,
                              default='created')

    client = models.ManyToManyField(Client, verbose_name='Клиенты рассылки')
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE, **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Владелец',
                              **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активная')

    def __str__(self):
        return f'Начало {self.start_point}, повтор {self.period}, статус {self.status} '

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('set_is_active', 'Изменить aктивность'),
        ]


class Log(models.Model):
    """Логи рассылки"""
    """Статус рассылки для лога"""
    LOG_CHOICES = [
        (True, 'Успешно'),
        (False, 'Ошибка')
    ]
    attempt_time = models.DateTimeField(verbose_name='Дата и время последней попытки', **NULLABLE)
    attempt_status = models.CharField(max_length=10, verbose_name='Статус попытки', choices=LOG_CHOICES, default=True)
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE)

    mailing = models.ForeignKey(Mailing, verbose_name='Рассылка', on_delete=models.CASCADE, **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент рассылки', **NULLABLE)

    def __str__(self):
        return f'Попытка отправки {self.attempt_time}, статус - {self.attempt_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, Message
from services import StileFormMixin


class ClientForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MailingForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'


class MessageForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

mailing/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404
from django.shortcuts import get_object_or_404, redirect

from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Post
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Mailing, Client, Message, Log


class HomePageView(TemplateView):
    """Отображение домашней страницы"""
    template_name = 'mailing/main_page.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_count'] = Mailing.objects.all().count()
        context_data['active_mailing_count'] = Mailing.objects.filter(is_active=True, ).count()
        context_data['clients_count'] = Client.objects.all().distinct().count()
        context_data['posts'] = Post.objects.all()[:3]

        return context_data


class MailingListView(LoginRequiredMixin, ListView):
    """Просмотр списка рассылок"""
    model = Mailing


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Просмотр рассылки по id"""
    model = Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Создание рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser or self.object.owner != self.request.user:
            raise Http404
        return self.object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление рассылки"""
    model = Mailing
    success_url = reverse_lazy('mailing:home')


class ClientListView(ListView):
    """Просмотр списка клиентов"""
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Создание карточки клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование карточки клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MessageListView(LoginRequiredMixin, ListView):
    """Просмотр списка сообщений"""
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание карточки клиента"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')


class LogListView(ListView):
    """Просмотр списка логов"""
    model = Log

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(attempt_status=True).count()
        context_data['error'] = context_data['object_list'].filter(attempt_status=False).count()
        return context_data


@login_required
@permission_required('mailing.set_is_active')
def active_toggle(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)
    if mailing_item.is_active:
        mailing_item.is_active = False
    else:
        mailing_item.is_active = True
    mailing_item.save()
    return redirect(reverse('mailing:mailing_list'))

mailing/templates/mailing/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SkyService</title>
    {% load static %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
{% include 'mailing/includes/inc_menu.html' %}
<body>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyService</h1>
    <p class="lead">SkyService - это сервис для создания, настройки и редактирования рассылок.
    Для работы с сервисом выполните вход или зарегистрируйтесь.</p>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyService
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Карточка клиента
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Схранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Добавить карточку клиента</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card md-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                        <a href="{#}"
                           class="btn btn-sm btn-outline-secondary">Показать</a>


                        <a href="{% url 'mailing:client_edit' object.pk %}"
                           type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>


                        <a href="{#}"
                           type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/log_list.html
{%  extends 'mailing/base.html'%}

{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Информация о логах рассылок</h5></div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Количество всего</td>
                            <td>{{ all }}</td>
                        </tr>
                        <tr>
                            <td>Количество успешных рассылок</td>
                            <td>{{ success }}</td>
                        </tr>
                        <tr>
                            <td>Количество неудвчных рассылок</td>
                            <td>{{ error }}</td>
                    </table>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
        </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{%  extends 'mailing/base.html'%}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {{ object.client }}
                </div>
                <div class="card-body">
                    {{ object.message }}
                </div>
                <div class="card-footer">
                    {{ object.start_point }}, {{ object.stop_point }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <form class="row" method="post">
            <div class="card">
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить рассылку</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
        <div class="card md-4 box-shadow">
            <div class="card-body">
               <p class="card-text"> {{ object }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'mailing:mailing_view' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Показать</a>
                        <a href="{% url 'mailing:mailing_edit' object.pk %}"
                            type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                        <a href="{% url 'mailing:mailing_delete' object.pk %}"
                            type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/main_page.html
{%  extends 'mailing/base.html'%}

{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Информация о рассылках</h5></div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Количество рассылок всего</td>
                            <td>{{ mailing_count}}</td>
                        </tr>
                        <tr>
                            <td>Количество активных рассылок</td>
                            <td>{{ active_mailing_count }}</td>
                        </tr>
                        <tr>
                            <td>Количество уникальных клиентов для рассылок</td>
                            <td>{{ clients_count }}</td>
                        </tr>

                    </table>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Посты</h5></div>
                <div class="card-body">
                    {% for post in posts %}
                        {{ post.title }}
                    {% endfor %}
                </div>

                <div class="card-footer"></div>

            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Новое сообщение
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Схранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить сообщение</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
        <div class="card md-4 box-shadow">
            <div class="card-body">
               <p class="card-text"> {{ object }}</p>
                <div class="d-flex justify-content-between align-items-center">
<!--                    <div class="btn-group">-->
<!--                        <a href="{# url 'mailing:mailing_view' object.pk #}"-->
<!--                            class="btn btn-sm btn-outline-secondary">Показать</a>-->
<!--                        <a href="{# url 'mailing:mailing_edit' object.pk #}"-->
<!--                            type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>-->
<!--                        <a href="{# url 'mailing:mailing_delete' object.pk #}"-->
<!--                            type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}